-- This file is auto-generated by scripts/generate-schema.ts
-- DO NOT EDIT MANUALLY
-- Run `npm run generate-schema` to update.

CREATE TABLE card_definitions (
      id         INTEGER PRIMARY KEY,
      name       TEXT NOT NULL,
      definition TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE card_values (
      id                 INTEGER PRIMARY KEY,
      card_definition_id INTEGER NOT NULL REFERENCES card_definitions(id) ON DELETE CASCADE,
      story_part_id      INTEGER NOT NULL REFERENCES story_parts(id) ON DELETE CASCADE,
      version            INTEGER NOT NULL,
      data               JSON NOT NULL,
      parent_version_id  INTEGER NULL REFERENCES card_values(id),
      is_obsolete        BOOLEAN DEFAULT FALSE,
      created_at         DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (card_definition_id, story_part_id, version)
    );

CREATE TABLE lore_nodes (
      id             INTEGER PRIMARY KEY,
      parent_id      INTEGER NULL REFERENCES lore_nodes(id) ON DELETE CASCADE,
      name           TEXT NOT NULL,
      content        TEXT,
      position       INTEGER DEFAULT 0,
      status         TEXT NOT NULL DEFAULT 'ACTIVE',
      to_be_deleted  INTEGER NOT NULL DEFAULT 0,
      created_at     DATETIME DEFAULT CURRENT_TIMESTAMP, word_count  INTEGER NOT NULL DEFAULT 0, char_count  INTEGER NOT NULL DEFAULT 0, byte_count  INTEGER NOT NULL DEFAULT 0, ai_sync_info TEXT NULL, changes_status TEXT NULL, review_base_content TEXT NULL, last_improve_instruction TEXT NULL, user_prompt TEXT NULL, system_prompt TEXT NULL, ai_settings TEXT,
      UNIQUE (parent_id, name)
    );

CREATE TABLE "plan_edges" (
      id           INTEGER PRIMARY KEY,
      from_node_id INTEGER NOT NULL REFERENCES plan_nodes(id) ON DELETE CASCADE,
      to_node_id   INTEGER NOT NULL REFERENCES plan_nodes(id) ON DELETE CASCADE,
      type         TEXT NOT NULL DEFAULT 'text',
      position     INTEGER DEFAULT 0,
      label        TEXT,
      template     TEXT
    );

CREATE TABLE plan_nodes (
      id            INTEGER PRIMARY KEY,
      parent_id     INTEGER NULL REFERENCES plan_nodes(id) ON DELETE CASCADE,
      title         TEXT NOT NULL,
      content       TEXT,
      position      INTEGER DEFAULT 0,
      created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
      type          TEXT NOT NULL DEFAULT 'text',
      x             REAL DEFAULT 0,
      y             REAL DEFAULT 0,
      user_prompt   TEXT,
      system_prompt TEXT,
      summary       TEXT,
      auto_summary  INTEGER DEFAULT 0,
      ai_sync_info  TEXT
    , word_count INTEGER NOT NULL DEFAULT 0, char_count INTEGER NOT NULL DEFAULT 0, byte_count INTEGER NOT NULL DEFAULT 0, changes_status TEXT NULL, review_base_content TEXT NULL, last_improve_instruction TEXT NULL, node_type_settings TEXT NULL, status TEXT NOT NULL DEFAULT 'EMPTY', ai_settings TEXT);

CREATE TABLE settings (
      key   TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );

CREATE TABLE story_parts (
      id                  INTEGER PRIMARY KEY,
      plan_node_version_id INTEGER NOT NULL REFERENCES plan_node_versions(id) ON DELETE CASCADE,
      version             INTEGER NOT NULL,
      content             TEXT NOT NULL,
      status              TEXT NOT NULL DEFAULT 'GENERATED',
      parent_version_id   INTEGER NULL REFERENCES story_parts(id),
      is_obsolete         BOOLEAN DEFAULT FALSE,
      created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (plan_node_version_id, version)
    );
