-- This file is auto-generated by scripts/generate-schema.ts
-- DO NOT EDIT MANUALLY
-- Run `npm run generate-schema` to update.
CREATE TABLE ai_call_stats (
  id INTEGER PRIMARY KEY,
  ts DATETIME NOT NULL,
  run_id TEXT NOT NULL,
  engine_id TEXT NOT NULL,
  model TEXT NOT NULL,
  purpose TEXT NOT NULL,
  prompt_cache_keys TEXT,
  node_title TEXT,
  node_type TEXT,
  instructions_chars INTEGER NOT NULL,
  input_chars INTEGER NOT NULL,
  output_chars INTEGER NOT NULL,
  input_tokens INTEGER,
  output_tokens INTEGER,
  cached_prompt_tokens INTEGER,
  duration_ms INTEGER NOT NULL,
  cost_usd REAL,
  success INTEGER NOT NULL,
  error_message TEXT,
  iteration_index INTEGER,
  reasoning_effort TEXT
);

CREATE TABLE ai_run_stats (
  id INTEGER PRIMARY KEY,
  run_id TEXT NOT NULL UNIQUE,
  started_at DATETIME NOT NULL,
  finished_at DATETIME,
  wall_time_ms INTEGER,
  template_file TEXT,
  engine_id TEXT,
  model TEXT,
  total_calls INTEGER NOT NULL DEFAULT 0,
  calls_by_purpose TEXT,
  sum_durations_ms INTEGER NOT NULL DEFAULT 0,
  total_input_tokens INTEGER,
  total_output_tokens INTEGER,
  total_cached_prompt_tokens INTEGER,
  cost_usd REAL,
  success INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE card_definitions (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  definition TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE card_values (
  id INTEGER PRIMARY KEY,
  card_definition_id INTEGER NOT NULL REFERENCES card_definitions (id) ON DELETE CASCADE,
  story_part_id INTEGER NOT NULL REFERENCES story_parts (id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  data JSON NOT NULL,
  parent_version_id INTEGER NULL REFERENCES card_values (id),
  is_obsolete BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (card_definition_id, story_part_id, version)
);

CREATE TABLE lore_nodes (
  id INTEGER PRIMARY KEY,
  parent_id INTEGER NULL REFERENCES lore_nodes (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  position INTEGER DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  to_be_deleted INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  word_count INTEGER NOT NULL DEFAULT 0,
  char_count INTEGER NOT NULL DEFAULT 0,
  byte_count INTEGER NOT NULL DEFAULT 0,
  ai_sync_info TEXT NULL,
  review_base_content TEXT NULL,
  ai_improve_instruction TEXT NULL,
  ai_user_prompt TEXT NULL,
  ai_settings TEXT,
  in_review INTEGER NOT NULL DEFAULT 0,
  ai_system_prompt TEXT NULL,
  width INTEGER NULL,
  height INTEGER NULL,
  UNIQUE (parent_id, title)
);

CREATE TABLE "plan_edges" (
  id INTEGER PRIMARY KEY,
  from_node_id INTEGER NOT NULL REFERENCES plan_nodes (id) ON DELETE CASCADE,
  to_node_id INTEGER NOT NULL REFERENCES plan_nodes (id) ON DELETE CASCADE,
  type TEXT NOT NULL DEFAULT 'text',
  position INTEGER DEFAULT 0,
  label TEXT,
  template TEXT
);

CREATE TABLE plan_nodes (
  id INTEGER PRIMARY KEY,
  parent_id INTEGER NULL REFERENCES plan_nodes (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  position INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL DEFAULT 'text',
  x REAL DEFAULT 0,
  y REAL DEFAULT 0,
  summary TEXT,
  ai_sync_info TEXT,
  word_count INTEGER NOT NULL DEFAULT 0,
  char_count INTEGER NOT NULL DEFAULT 0,
  byte_count INTEGER NOT NULL DEFAULT 0,
  review_base_content TEXT NULL,
  ai_improve_instruction TEXT NULL,
  node_type_settings TEXT NULL,
  status TEXT NOT NULL DEFAULT 'EMPTY',
  ai_settings TEXT,
  in_review INTEGER NOT NULL DEFAULT 0,
  width INTEGER NULL,
  height INTEGER NULL
);

CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);

CREATE TABLE story_parts (
  id INTEGER PRIMARY KEY,
  plan_node_version_id INTEGER NOT NULL REFERENCES plan_node_versions (id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'GENERATED',
  parent_version_id INTEGER NULL REFERENCES story_parts (id),
  is_obsolete BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (plan_node_version_id, version)
);

CREATE INDEX idx_ai_call_stats_lookup ON ai_call_stats (node_type, purpose, engine_id, model);

CREATE INDEX idx_ai_call_stats_run ON ai_call_stats (run_id);
