// This file is auto-generated by scripts/js-schemas-to-ts.ts
// DO NOT EDIT MANUALLY
// Run `npm run generate-code` to update.

export const PLAN_CONTAINER_NODE_TYPE_VALUES = ["for-each"] as const

export type PlanContainerNodeType = (typeof PLAN_CONTAINER_NODE_TYPE_VALUES)[number]

export const PLAN_NON_CONTAINER_NODE_TYPE_VALUES = [
  "text",
  "lore",
  "merge",
  "split",
  "fix-problems",
  "for-each-input",
  "for-each-output",
  "for-each-prev-outputs",
] as const

export type PlanNonContainerNodeType = (typeof PLAN_NON_CONTAINER_NODE_TYPE_VALUES)[number]

export const PLAN_EDGE_TYPE_VALUES = ["text", "textArray"] as const

export type PlanEdgeType = (typeof PLAN_EDGE_TYPE_VALUES)[number]

export type PlanNodeType = PlanContainerNodeType | PlanNonContainerNodeType
