// This file is auto-generated by scripts/js-schemas-to-ts.ts
// DO NOT EDIT MANUALLY
// Run `npm run generate-code` to update.

export const PLAN_EDGE_TYPE_VALUES = ["text", "textArray"] as const

export type PlanEdgeType = (typeof PLAN_EDGE_TYPE_VALUES)[number]
