// This file is auto-generated by scripts/js-schemas-to-ts.ts
// DO NOT EDIT MANUALLY
// Run `npm run generate-code` to update.

import type { PlanNodeType } from "./plan-node-types"

export interface ProjectTemplate {
  wizardScreens: WizardPage
  plan: TemplateProjectPlan
}

export interface WizardPage {
  fields: WizardField
}

export interface BaseWizardField {
  name: string
  label: string
  description?: string
  type: string
}

export interface WizardTextAreaField extends BaseWizardField {
  type: "textarea"
}

export interface WizardInputField extends BaseWizardField {
  type: "input"
}

export type WizardField = WizardInputField | WizardTextAreaField

export interface TemplateProjectPlan {
  nodes: TemplateProjectNode
}

export interface TemplateProjectNode {
  id: number
  title: string
  type: PlanNodeType
  content: string
  children?: TemplateProjectNode
  outputs: Record<string, any>[]
}
