// This file is auto-generated by scripts/js-schemas-to-ts.ts
// DO NOT EDIT MANUALLY
// Run `npm run generate-code` to update.

import type { PlanNodeType } from "./plan-node-types"
import type { PlanEdgeType } from "./plan-edge-types"

export interface ProjectTemplate {
  title: string
  wizardPages?: WizardPage[]
  plan: TemplateProjectPlan
}

export interface WizardPage {
  fields: WizardField
}

export interface BaseWizardField {
  name: string
  label: string
  description?: string
  type: string
}

export interface WizardTextAreaField extends BaseWizardField {
  type: "textarea"
}

export interface WizardInputField extends BaseWizardField {
  type: "input"
}

export type WizardField = WizardInputField | WizardTextAreaField

export interface TemplateProjectPlan {
  nodes: TemplateProjectNode
}

export interface TemplateProjectNode {
  id: number
  title: string
  type: PlanNodeType
  aiUserInstructions?: string[]
  content?: string[]
  children?: TemplateProjectNode
  inputs?: TemplateProjectNodeInput[]
}

export interface TemplateProjectNodeInput {
  sourceNodeId: number
  type: PlanEdgeType
}
