// This file is auto-generated by scripts/js-schemas-to-ts.ts
// DO NOT EDIT MANUALLY
// Run `npm run generate-code` to update.

import type { PlanNodeType } from "./plan-node-types"
import type { PlanEdgeType } from "./plan-edge-types"

export interface ProjectTemplate {
  $schema?: string
  label: string
  description: string
  wizardPages?: WizardPage[]
  lore?: TemplateProjectLore
  plan: TemplateProjectPlan
}

export interface WizardPage {
  id: string
  title: string
  description?: string
  fields: WizardField[]
}

export interface BaseWizardField {
  name: string
  label: string
  description?: string
  type: string
}

export interface WizardTextAreaField extends BaseWizardField {
  type: "textarea"
  placeholder?: string
}

export interface WizardInputField extends BaseWizardField {
  type: "input"
  placeholder?: string
}

export type WizardField = WizardInputField | WizardTextAreaField

export interface TemplateProjectLore {
  nodes: TemplateProjectLoreNode[]
}

export interface TemplateProjectLoreNode {
  id: number
  title: string
  content?: string[]
  children?: TemplateProjectLoreNode[]
}

export interface TemplateProjectPlan {
  nodes: TemplateProjectPlanNode[]
}

export interface TemplateProjectPlanNode {
  id: number
  title: string
  type: PlanNodeType
  aiUserInstructions?: string[]
  nodeTypeSettings?: Record<string, any>
  content?: string[]
  children?: TemplateProjectPlanNode[]
  inputs?: TemplateProjectPlanNodeInput[]
}

export interface TemplateProjectPlanNodeInput {
  sourceNodeId: number
  type: PlanEdgeType
}
