#!/usr/bin/env tsx

import Database from 'better-sqlite3'
import { migrateDatabase } from '../src/backend/db/migrations'
import fs from 'fs'
import path from 'path'

function getSchema(db: Database.Database): string {
  // Query all CREATE statements from sqlite_master, excluding internal tables
  const rows = db.prepare(`
    SELECT type, name, sql
    FROM sqlite_master
    WHERE sql IS NOT NULL
      AND name NOT LIKE 'sqlite_%'
    ORDER BY type, name
  `).all() as Array<{ type: string; name: string; sql: string }>

  const statements: string[] = []
  for (const row of rows) {
    // Ensure each statement ends with a semicolon
    let sql = row.sql.trim()
    if (!sql.endsWith(';')) sql += ';'
    statements.push(sql)
  }

  // Add a blank line between statements for readability
  return statements.join('\n\n') + '\n'
}

function main() {
  // Create an in-memory database
  const db = new Database(':memory:')

  try {
    // Apply all migrations
    migrateDatabase(db)

    // Generate schema
    const schema = getSchema(db)

    // Write to file
    const schemaPath = path.resolve(__dirname, '../src/backend/db/schema.sql')
    fs.writeFileSync(schemaPath, `-- This file is auto-generated by scripts/generate-schema.ts
-- DO NOT EDIT MANUALLY
-- Run \`npm run generate-schema\` to update.

${schema}`)
    console.log(`Schema written to ${schemaPath}`)
  } finally {
    db.close()
  }
}

if (require.main === module) {
  main()
}