#!/usr/bin/env tsx

import Database from 'better-sqlite3'
import { migrateDatabase } from '../dist/backend/db/migrations.js'
import { writeFileSync, copyFileSync, existsSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

function getSchema(db: Database.Database): string {
  // Query all CREATE statements from sqlite_master, excluding internal tables
  const rows = db.prepare(`
    SELECT type, name, sql
    FROM sqlite_master
    WHERE sql IS NOT NULL
      AND name NOT LIKE 'sqlite_%'
    ORDER BY type, name
  `).all() as Array<{ type: string; name: string; sql: string }>

  const statements: string[] = []
  for (const row of rows) {
    // Ensure each statement ends with a semicolon
    let sql = row.sql.trim()
    if (!sql.endsWith(';')) sql += ';'
    statements.push(sql)
  }

  // Add a blank line between statements for readability
  return statements.join('\n\n') + '\n'
}

function ensureSchemaFile() {
  const srcSchemaPath = resolve(__dirname, '../src/backend/db/schema.sql')
  const distSchemaPath = resolve(__dirname, '../dist/backend/db/schema.sql')
  const distRootSchemaPath = resolve(__dirname, '../dist/schema.sql')
  const distDir = dirname(distSchemaPath)
  const distRootDir = dirname(distRootSchemaPath)

  if (!existsSync(distDir)) {
    mkdirSync(distDir, { recursive: true })
  }
  if (!existsSync(distRootDir)) {
    mkdirSync(distRootDir, { recursive: true })
  }
  // Copy schema.sql to dist so that migrateDatabase can find it
  if (existsSync(srcSchemaPath)) {
    copyFileSync(srcSchemaPath, distSchemaPath)
    copyFileSync(srcSchemaPath, distRootSchemaPath)
    console.log(`Copied schema.sql to ${distSchemaPath} and ${distRootSchemaPath}`)
  } else {
    // If schema.sql doesn't exist, create an empty one (should not happen)
    writeFileSync(srcSchemaPath, '')
    copyFileSync(srcSchemaPath, distSchemaPath)
    copyFileSync(srcSchemaPath, distRootSchemaPath)
    console.warn(`Schema file not found, created empty at ${srcSchemaPath}`)
  }
}

function main() {
  // Ensure schema.sql exists in dist
  ensureSchemaFile()

  // Create an in-memory database
  const db = new Database(':memory:')

  try {
    // Apply all migrations, skipping schema load to apply migrations from zero
    migrateDatabase(db, true)

    // Generate schema
    const schema = getSchema(db)

    // Write to file (overwrites src schema.sql)
    const schemaPath = resolve(__dirname, '../src/backend/db/schema.sql')
    writeFileSync(schemaPath, `-- This file is auto-generated by scripts/generate-schema.ts
-- DO NOT EDIT MANUALLY
-- Run \`npm run generate-schema\` to update.

${schema}`)
    console.log(`Schema written to ${schemaPath}`)
  } finally {
    db.close()
  }
}

main()